from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

def test_post_idea():
    driver = webdriver.Chrome()

    try:
        # STEP 1: LOGIN (Required for Idea Marketplace API)
        print("1. Navigating to login page...")
        driver.get("http://localhost:5173/login")

        wait = WebDriverWait(driver, 10)
        email_input = wait.until(EC.presence_of_element_located((By.XPATH, "//input[@type='email']")))
        password_input = driver.find_element(By.XPATH, "//input[@type='password']")
        submit_login = driver.find_element(By.XPATH, "//button[@type='submit']")

        print("2. Entering valid credentials...")
        email_input.send_keys("azadi4@gmail.com") 
        password_input.send_keys("azadi4")
        submit_login.click()

        # Wait for redirect to profile to confirm login success
        wait.until(EC.url_contains("/profile"))
        print("✅ Logged in successfully!")

        # STEP 2: NAVIGATE TO IDEAS
        print("3. Navigating to Idea Marketplace...")
        # Assume the route is /ideas or /marketplace 
        # (Change /ideas to whatever your actual route is in App.tsx!)
        driver.get("http://localhost:5173/ideas")

        # STEP 3: OPEN MODAL & SUBMIT
        print("4. Clicking 'Pitch an Idea'...")
        pitch_btn = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Pitch an Idea')]")))
        pitch_btn.click()

        print("5. Filling out the idea form...")
        # Wait for modal inputs to appear
        title_input = wait.until(EC.presence_of_element_located((By.XPATH, "//input[@placeholder='e.g. AI-driven Cancer Detection']")))
        desc_input = driver.find_element(By.XPATH, "//textarea[@placeholder='Describe your idea...']")
        area_input = driver.find_element(By.XPATH, "//input[@placeholder='e.g. Machine Learning']")
        skills_input = driver.find_element(By.XPATH, "//input[@placeholder='e.g. Python, React']")
        
        # Locate the submit button inside the modal
        submit_idea = driver.find_element(By.XPATH, "//button[text()='Post Idea']")

        # Enter the mock data
        title_input.send_keys("Automated Test Idea via Selenium")
        desc_input.send_keys("This is a mock idea generated by our automated testing script to ensure the creation workflow functions.")
        area_input.send_keys("Software Engineering")
        skills_input.send_keys("Selenium, Python, QA")
        
        print("6. Submitting the idea...")
        submit_idea.click()

        # Wait for the network request to finish and modal to close
        time.sleep(3) 
        print("✅ Idea test finished! The modal should have closed and the new idea should appear on the page.")

    except Exception as e:
        print("❌ Test failed with exception:", e)

    finally:
        print("Closing browser...")
        driver.quit()

if __name__ == "__main__":
    test_post_idea()
